FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Commande par défaut pour exécuter la synchronisation
CMD ["python", "cassandra_to_elasticsearch.py"]
